channels:
  - conda-forge
  - dharpa
host_requirements:
  - pip
  - python
  - setuptools<=63
  - setuptools_scm
  - setuptools_scm_git_archive

test:
  imports:
    - kiara_plugin.tabular
  source_files:
    - tests
    - examples
  commands:
    - kiara module list
